### PR TITLE
Fixed regex error with Flake8 5.0.4.

### PR DESCRIPTION
**Pull request by Aspect1103**

### CODE REVIEW

**Comment by Aspect1103** [comment]
Fixes #44

**Comment by silasary** [comment]
@domdfcoding Can this get merged?

**Comment by Aspect1103** [comment]
It seems the plugin is no longer maintained. It would be nice if we could get an update.

**Comment by sshishov** [comment]
@domdfcoding could you please merge it if you still maintain the plugin

**Pull request closed without merging**
